Feature/add cookies pref
ONSdigital/dp-design-system pull request #169
Opened 2023-06-15 08:56 UTC by JoshSinghONS

### What

Updated Regex
Added cookies-pref.js

### How to review

LGTM

### Who can review

Anyone.

2023-06-16 11:18 UTC, mr-nick17 reviewed
You need to try and fix the audit problems. Try updating node to v20 (or bumping to at least v18-LTS) and then update the dependencies; this should hopefully resolve the audit problem

2023-06-16 11:18 UTC, mr-nick17 commented on auditjs.json
> +      "reason":"decode-uri-component ... something something ... not sure what to put here."
The reason why you are adding it to the exclude list needs to be put here see inspiration above

2023-06-16 11:18 UTC, mr-nick17 commented on src/js/dp/cookies-pref.js
> +});
Empty EOF line is missing

2023-06-16 11:18 UTC, mr-nick17 commented on package-lock.json
> +      "version": "3.1.0",
This is changing the version to a lower version that will also cause the audit issues that you're ignoring

2023-06-20 10:56 UTC, JoshSinghONS commented
I am at a loss. 

The latest commit allows me to pass the audit on my local machine where I run node 20, I'm not sure what the CI/CD pipeline uses.

From what I can tell when I keep resolutions instead of overrides glob-parent does not change it's version for some of the projects its a dependent for

Using "npm ls glob-parent"

dp-design-system@2.0.0 /Users/joshuasingh/src/github.com/ONSdigital/dp-design-system
├─┬ @babel/cli@7.22.5
│ └─┬ chokidar@3.5.3
│   └── glob-parent@5.1.2
├─┬ babel-eslint@10.1.0
│ └─┬ eslint@8.43.0
│   └── glob-parent@6.0.2
└─┬ gulp@4.0.2
  ├─┬ glob-watcher@5.0.5
  │ └─┬ chokidar@2.1.8
  │   └── glob-parent@3.1.0
  └─┬ vinyl-fs@3.0.3
    └─┬ glob-stream@6.1.0
      └── glob-parent@3.1.0
      
You can see the dependencies gulp 4.0.2 has uses an outdated version of glob-parent, alas gulp 4.0.2 is the latest version. Using the overrides property bumps the lower glob-parents to the latest version and that works locally as mentioned but the CI/CD audit still fails.

Any ideas?

2023-06-22 11:45 UTC, lindenmckenzie requested changes
See comment

2023-06-22 11:45 UTC, lindenmckenzie commented on ci/build.yml
> +    tag: latest
Think we should still be using the specific tag here rather than `latest`

2023-06-22 11:46 UTC, lindenmckenzie commented on ci/build.yml
> +    tag: latest
see https://github.com/ONSdigital/florence/blob/develop/ci/lint.yml

2023-06-22 13:19 UTC, lindenmckenzie submitted a review, later dismissed

2023-06-26 11:55 UTC, merged