#826: Create a basic, accessible, reusable map component (no boundaries)
ONSdigital/dp-design-system pull request #57
Opened 2022-02-17 18:52 UTC by joegasewicz

### What

Describe what you have changed and why.

### How to review

Describe the steps required to test the changes.

### Who can review

Describe who worked on the changes, so that other people can review.

2022-02-18 11:57 UTC, joegasewicz commented on src/js/dp/map.js
> +    let mapZoom = _getMapZoom(mapElem);
This should have been a const

2022-02-18 11:59 UTC, joegasewicz commented on src/js/dp/map.js
> +    console.log("Loading map...")
needs removing

2022-03-08 18:03 UTC, gilesburdett commented
Would it be preferrable to move the images into the `cdn.ons.gov.uk-assets` repository?

https://github.com/ONSdigital/cdn.ons.gov.uk-assets/tree/master/assets/images

2022-03-08 18:29 UTC, gilesburdett requested changes

2022-03-08 18:29 UTC, gilesburdett commented on src/js/dp/map.js
> +    if (mapCenter.length < 2) throw new Error(centerErrorMsg);
```suggestion
    if (mapCenter.length < 2) {
        throw new Error(centerErrorMsg);
    }
```

2022-03-08 18:29 UTC, gilesburdett commented on src/js/dp/map.js
> +    mapCenter = mapCenter.map(center => {
Counterintuitively the radix does not default to 10:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/parseInt#description

```suggestion
    mapCenter = mapCenter.map(center => parseInt(center, 10));
```

2022-03-08 18:29 UTC, gilesburdett commented on src/js/dp/map.js
> +        mapZoom =  parseInt(mapEl.dataset.zoom)
```suggestion
        mapZoom =  parseInt(mapEl.dataset.zoom, 10);
```

2022-03-08 18:29 UTC, gilesburdett commented on src/js/dp/map.js
> +    let mapZoom = parseInt(mapEl.dataset.zoom)
```suggestion
    let mapZoom = parseInt(mapEl.dataset.zoom, 10);
```

2022-03-08 18:29 UTC, gilesburdett commented on src/js/dp/map.js
> +const _getToken = (mapEl) => {
const _getToken = (mapEl) => mapEl.dataset.token;

2022-03-08 18:29 UTC, gilesburdett commented on src/js/dp/map.js
> +            this._controlElements = val.map((elem, i) => {
Unused index

```suggestion
            this._controlElements = val.map((elem) => {
```

2022-03-08 18:29 UTC, gilesburdett commented on src/js/dp/map.js
> +
```suggestion
switch (e.which) {
    case Keys.R:
        this._onReset(e);
        break;
    case Keys.Escape:
        canvas.blur(); 
        break;
}
```

or `if` ... `else if` without the `return` in the first block if `switch` isn't the house style

2022-03-08 18:30 UTC, gilesburdett commented
Will this work with 2+ maps on a page, or is it expected that that would never occur?

2022-03-09 08:24 UTC, mr-nick17 commented
My main concern is that this implementation will load all the map js and css for pages that instantiate the `dp-design-system` regardless of whether there is a map on the page. What's the difference in payload?

2022-03-09 19:29 UTC, joegasewicz commented
> My main concern is that this implementation will load all the map js and css for pages that instantiate the `dp-design-system` regardless of whether there is a map on the page. What's the difference in payload?

Solution for this is coming in another pr, will update with a link asap, thank you

2022-05-20 13:36 UTC, closed without merging